#!/usr/bin/env node

/**
 * Export Scrydex page data as SQL inserts for price_snapshots.
 *
 * This is the no-Supabase-credentials path: the script calls Scrydex locally,
 * then writes a SQL file you can paste/run in the Supabase/Lovable SQL editor.
 *
 * Env:
 *   SCRYDEX_KEY      required
 *   SCRYDEX_TEAM     optional, default collectiblez
 *
 * Examples:
 *   SCRYDEX_KEY=... node scripts/scrydex-tools/export_snapshot_sql.mjs --pages 25
 *   SCRYDEX_KEY=... node scripts/scrydex-tools/export_snapshot_sql.mjs --set me4
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const EARLY_VARIANT_SET_IDS = new Set([
  "base1", "base2", "basep", "ecard1", "ecard2", "ecard3",
  "ex1", "ex2", "ex3", "ex4", "ex5", "ex6", "ex7", "ex8", "ex9",
  "ex10", "ex11", "ex12", "ex13", "ex14", "ex15", "ex16",
  "gym1", "gym2",
  "neo1", "neo2", "neo3", "neo4",
]);

const MODERN_PRIORITY = ["normal", "holofoil", "reverseHolofoil"];
const PAGE_SIZE = 100;

function arg(name, fallback = undefined) {
  const idx = process.argv.indexOf(`--${name}`);
  if (idx === -1) return fallback;
  return process.argv[idx + 1] ?? fallback;
}

function flag(name) {
  return process.argv.includes(`--${name}`);
}

function normalizeScrydexCardId(id) {
  let next = id.replace(/^me0?(\d+)\.5(-)/, (_m, n, sep) => `me${n}pt5${sep}`);
  next = next.replace(/^me(\d+)\.5(-)/, (_m, n, sep) => `me${n}pt5${sep}`);
  next = next.replace(/^me0+(\d+)(-)/, (_m, n, sep) => `me${n}${sep}`);
  return next;
}

function claimCard(seen, rawId) {
  const normId = normalizeScrydexCardId(rawId);
  const isCanonical = rawId === normId;
  const prev = seen.get(normId);
  if (prev === undefined) {
    seen.set(normId, isCanonical);
    return true;
  }
  if (prev === true) return false;
  if (!isCanonical) return false;
  seen.set(normId, true);
  return true;
}

function isVintageVariantName(name) {
  const n = String(name ?? "").toLowerCase();
  return n.includes("shadowless") || n.includes("1stedition") || n.includes("firstedition") || n.startsWith("unlimited");
}

function isEarlyVariantSet(card) {
  const expansionId = card.expansion?.id?.toLowerCase();
  const cardPrefix = card.id?.split("-")[0]?.toLowerCase();
  return Boolean(
    (expansionId && EARLY_VARIANT_SET_IDS.has(expansionId)) ||
    (cardPrefix && EARLY_VARIANT_SET_IDS.has(cardPrefix))
  );
}

function extractAllVariantPrices(card) {
  const all = [];
  for (const v of card.variants ?? []) {
    const price = v.prices?.find(
      (x) => x.condition === "NM" && x.type === "raw" && x.currency === "USD" && x.market > 0,
    )?.market;
    if (price && price > 0) all.push({ variant: v.name, price });
  }

  if (all.length === 0) return [];

  const isVintage = isEarlyVariantSet(card) && all.some((vp) => isVintageVariantName(vp.variant));
  if (isVintage) return all;

  const best = MODERN_PRIORITY.map((p) => all.find((vp) => vp.variant === p)).find(Boolean) ?? all[0];
  return [{ variant: "normal", price: best.price }];
}

function sqlString(value) {
  if (value == null) return "''";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function cardSnapshotId(cardId, variant) {
  const id = normalizeScrydexCardId(cardId);
  return variant === "normal" ? id : `${id}::${variant}`;
}

function shouldKeepCard(card) {
  if (card.language_code && card.language_code !== "EN") return false;
  if (card.expansion?.language_code !== "EN") return false;
  if (card.expansion?.is_online_only) return false;
  const series = String(card.expansion?.series ?? "").toLowerCase();
  if (series.includes("pocket")) return false;
  return true;
}

async function scrydexFetch(endpoint, headers) {
  const url = `https://api.scrydex.com${endpoint}`;
  const res = await fetch(url, { headers });
  const text = await res.text();
  let data;
  try {
    data = JSON.parse(text);
  } catch {
    throw new Error(`Scrydex ${res.status} non-JSON response: ${text.slice(0, 200)}`);
  }
  if (!res.ok) throw new Error(`Scrydex ${res.status}: ${JSON.stringify(data).slice(0, 300)}`);
  return data;
}

function buildEndpoint(page, setId, orderBy) {
  const params = new URLSearchParams();
  params.set("page", String(page));
  params.set("page_size", String(PAGE_SIZE));
  params.set("include", "prices");
  if (setId) params.set("q", `expansion.id:${setId}`);
  else params.set("orderBy", orderBy);
  return `/pokemon/v1/cards?${params.toString()}`;
}

function buildSql(rows, meta) {
  const lines = [];
  lines.push("-- Generated by scripts/scrydex-tools/export_snapshot_sql.mjs");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Source: ${meta.source}`);
  lines.push(`-- Rows: ${rows.length}`);
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  for (let i = 0; i < rows.length; i += 500) {
    const chunk = rows.slice(i, i + 500);
    lines.push("INSERT INTO public.price_snapshots (card_id, card_name, set_name, price, recorded_at)");
    lines.push("VALUES");
    lines.push(chunk.map((r) =>
      `  (${sqlString(r.card_id)}, ${sqlString(r.card_name)}, ${sqlString(r.set_name)}, ${Number(r.price).toFixed(2)}, ${sqlString(r.recorded_at)})`
    ).join(",\n"));
    lines.push("ON CONFLICT (card_id, recorded_at) DO UPDATE SET");
    lines.push("  price = EXCLUDED.price,");
    lines.push("  card_name = COALESCE(NULLIF(EXCLUDED.card_name, ''), public.price_snapshots.card_name),");
    lines.push("  set_name = COALESCE(NULLIF(EXCLUDED.set_name, ''), public.price_snapshots.set_name);");
    lines.push("");
  }

  lines.push("SELECT public.refresh_latest_card_prices();");
  lines.push("");
  lines.push("-- Quick spot checks after the refresh:");
  lines.push("SELECT card_id, card_name, set_name, price, recorded_at, updated_at");
  lines.push("FROM public.latest_card_prices");
  lines.push("WHERE card_id IN ('me4-116')");
  lines.push("ORDER BY card_id;");
  lines.push("");
  lines.push("COMMIT;");
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const apiKey = process.env.SCRYDEX_KEY || process.env.SCRYDEX_API_KEY;
  const teamId = process.env.SCRYDEX_TEAM || process.env.SCRYDEX_TEAM_ID || "collectiblez";
  if (!apiKey) {
    throw new Error("Missing SCRYDEX_KEY env var.");
  }

  const pages = Math.max(1, Number(arg("pages", "25")) || 25);
  const startPage = Math.max(1, Number(arg("start-page", "1")) || 1);
  const orderBy = arg("orderBy", "-expansion.release_date");
  const setId = arg("set", "");
  const recordedAt = arg("date", new Date().toISOString().split("T")[0]);
  const outPath = arg(
    "out",
    path.join("scripts", "scrydex-tools", `scrydex_snapshot_${setId || `${startPage}_${pages}`}_${recordedAt}.sql`),
  );

  const headers = { "X-Api-Key": apiKey, "X-Team-ID": teamId };
  const seen = new Map();
  const rows = [];
  let fetchedCards = 0;
  let skippedCards = 0;

  for (let offset = 0; offset < pages; offset++) {
    const page = startPage + offset;
    const endpoint = buildEndpoint(page, setId, orderBy);
    console.error(`Fetching ${endpoint}`);
    const result = await scrydexFetch(endpoint, headers);
    const cards = result.data ?? [];
    fetchedCards += cards.length;
    if (cards.length === 0) break;

    for (const card of cards) {
      if (!shouldKeepCard(card)) {
        skippedCards++;
        continue;
      }
      const variantPrices = extractAllVariantPrices(card);
      if (variantPrices.length === 0) {
        skippedCards++;
        continue;
      }
      if (!claimCard(seen, card.id)) {
        skippedCards++;
        continue;
      }
      for (const vp of variantPrices) {
        rows.push({
          card_id: cardSnapshotId(card.id, vp.variant),
          card_name: card.name ?? "",
          set_name: card.expansion?.name ?? "",
          price: vp.price,
          recorded_at: recordedAt,
        });
      }
    }
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, buildSql(rows, {
    source: setId ? `set ${setId}` : `${pages} page(s) from page ${startPage}, orderBy=${orderBy}`,
  }));

  console.error(`Fetched cards: ${fetchedCards}`);
  console.error(`SQL rows: ${rows.length}`);
  console.error(`Skipped cards: ${skippedCards}`);
  console.error(`Wrote: ${outPath}`);

  if (flag("print-summary")) {
    console.log(JSON.stringify({ fetchedCards, rows: rows.length, skippedCards, outPath }, null, 2));
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
