-- Seed game_card_pool with 300 cards (auto-generated)
INSERT INTO public.game_card_pool (card_id, name, image_small) VALUES
  ('sv8pt5-145', 'Teal Mask Ogerpon ex', 'https://images.scrydex.com/pokemon/sv8pt5-145/small'),
  ('swsh45sv-SV033', 'Snom', 'https://images.scrydex.com/pokemon/swsh45sv-SV033/small'),
  ('sv1-214', 'Greavard', 'https://images.scrydex.com/pokemon/sv1-214/small'),
  ('me3-90', 'Rowlet', 'https://images.scrydex.com/pokemon/me3-90/small'),
  ('me2-109', 'Mega Charizard X ex', 'https://images.scrydex.com/pokemon/me2-109/small'),
  ('swsh1-91', 'Indeedee V', 'https://images.scrydex.com/pokemon/swsh1-91/small'),
  ('sv10-211', 'Dondozo ex', 'https://images.scrydex.com/pokemon/sv10-211/small'),
  ('sm6-141', 'Beast Ring', 'https://images.scrydex.com/pokemon/sm6-141/small'),
  ('me2pt5-245', 'Galarian Obstagoon', 'https://images.scrydex.com/pokemon/me2pt5-245/small'),
  ('sv10-119', 'Team Rocket''s Nidoking ex', 'https://images.scrydex.com/pokemon/sv10-119/small'),
  ('xy8-159', 'M Mewtwo-EX', 'https://images.scrydex.com/pokemon/xy8-159/small'),
  ('swsh2-198', 'Malamar VMAX', 'https://images.scrydex.com/pokemon/swsh2-198/small'),
  ('sv2-207', 'Quaxwell', 'https://images.scrydex.com/pokemon/sv2-207/small'),
  ('swsh10-17', 'Hisuian Lilligant V', 'https://images.scrydex.com/pokemon/swsh10-17/small'),
  ('swsh8-273', 'Chili & Cilan & Cress', 'https://images.scrydex.com/pokemon/swsh8-273/small'),
  ('swsh6-216', 'Karen''s Conviction', 'https://images.scrydex.com/pokemon/swsh6-216/small'),
  ('sma-SV12', 'Frogadier', 'https://images.scrydex.com/pokemon/sma-SV12/small'),
  ('ex6-106', 'Clefable ex', 'https://images.scrydex.com/pokemon/ex6-106/small'),
  ('swsh7-232', 'Stormy Mountains', 'https://images.scrydex.com/pokemon/swsh7-232/small'),
  ('swsh3-179', 'Centiskorch V', 'https://images.scrydex.com/pokemon/swsh3-179/small'),
  ('sma-SV82', 'Cynthia', 'https://images.scrydex.com/pokemon/sma-SV82/small'),
  ('sm10-120', 'Lucario & Melmetal-GX', 'https://images.scrydex.com/pokemon/sm10-120/small'),
  ('swsh12-35', 'Omastar V', 'https://images.scrydex.com/pokemon/swsh12-35/small'),
  ('swsh3-183', 'Scizor V', 'https://images.scrydex.com/pokemon/swsh3-183/small'),
  ('sm8-222', 'Sigilyph-GX', 'https://images.scrydex.com/pokemon/sm8-222/small'),
  ('sv8pt5-156', 'Sylveon ex', 'https://images.scrydex.com/pokemon/sv8pt5-156/small'),
  ('swsh1-206', 'Snorlax VMAX', 'https://images.scrydex.com/pokemon/swsh1-206/small'),
  ('swsh12pt5-151', 'Volo', 'https://images.scrydex.com/pokemon/swsh12pt5-151/small'),
  ('ex15-99', 'Tyranitar ex δ', 'https://images.scrydex.com/pokemon/ex15-99/small'),
  ('sm12-4', 'Vileplume-GX', 'https://images.scrydex.com/pokemon/sm12-4/small'),
  ('sv10-187', 'Team Rocket''s Spidops', 'https://images.scrydex.com/pokemon/sv10-187/small'),
  ('sm9-191', 'Eevee & Snorlax-GX', 'https://images.scrydex.com/pokemon/sm9-191/small'),
  ('me1-156', 'Mega Camerupt ex', 'https://images.scrydex.com/pokemon/me1-156/small'),
  ('swsh35-22', 'Alcremie V', 'https://images.scrydex.com/pokemon/swsh35-22/small'),
  ('sm3-160', 'Noivern-GX', 'https://images.scrydex.com/pokemon/sm3-160/small'),
  ('swsh5-161', 'Phoebe', 'https://images.scrydex.com/pokemon/swsh5-161/small'),
  ('rsv10pt5-101', 'Litwick', 'https://images.scrydex.com/pokemon/rsv10pt5-101/small'),
  ('xy5-154', 'M Aggron-EX', 'https://images.scrydex.com/pokemon/xy5-154/small'),
  ('zsv10pt5-123', 'Golurk', 'https://images.scrydex.com/pokemon/zsv10pt5-123/small'),
  ('sv2-27', 'Wo-Chien ex', 'https://images.scrydex.com/pokemon/sv2-27/small'),
  ('sv9-168', 'Furret', 'https://images.scrydex.com/pokemon/sv9-168/small'),
  ('sm9-159', 'Celebi & Venusaur-GX', 'https://images.scrydex.com/pokemon/sm9-159/small'),
  ('swsh5-151', 'Single Strike Urshifu V', 'https://images.scrydex.com/pokemon/swsh5-151/small'),
  ('swsh7-168', 'Trevenant V', 'https://images.scrydex.com/pokemon/swsh7-168/small'),
  ('swsh5-166', 'Tapu Koko VMAX', 'https://images.scrydex.com/pokemon/swsh5-166/small'),
  ('sv8pt5-23', 'Vaporeon ex', 'https://images.scrydex.com/pokemon/sv8pt5-23/small'),
  ('swsh8-246', 'Tsareena V', 'https://images.scrydex.com/pokemon/swsh8-246/small'),
  ('xy9-115', 'M Gyarados-EX', 'https://images.scrydex.com/pokemon/xy9-115/small'),
  ('me1-36', 'Mega Abomasnow ex', 'https://images.scrydex.com/pokemon/me1-36/small'),
  ('sm10-210', 'Janine', 'https://images.scrydex.com/pokemon/sm10-210/small'),
  ('swsh9-172', 'Roseanne''s Backup', 'https://images.scrydex.com/pokemon/swsh9-172/small'),
  ('sv6-171', 'Poltchageist', 'https://images.scrydex.com/pokemon/sv6-171/small'),
  ('swsh12-203', 'Brandon', 'https://images.scrydex.com/pokemon/swsh12-203/small'),
  ('sv5-187', 'Incineroar ex', 'https://images.scrydex.com/pokemon/sv5-187/small'),
  ('swsh10-211', 'Choice Belt', 'https://images.scrydex.com/pokemon/swsh10-211/small'),
  ('swsh12tg-TG21', 'Duraludon VMAX', 'https://images.scrydex.com/pokemon/swsh12tg-TG21/small'),
  ('swsh4-170', 'Pikachu V', 'https://images.scrydex.com/pokemon/swsh4-170/small'),
  ('sma-SV94', 'Tapu Lele-GX', 'https://images.scrydex.com/pokemon/sma-SV94/small'),
  ('swsh12-195', 'Worker', 'https://images.scrydex.com/pokemon/swsh12-195/small'),
  ('me2pt5-10', 'Mega Meganium ex', 'https://images.scrydex.com/pokemon/me2pt5-10/small'),
  ('me2pt5-61', 'Mega Eelektross ex', 'https://images.scrydex.com/pokemon/me2pt5-61/small'),
  ('ex10-108', 'Scizor ex', 'https://images.scrydex.com/pokemon/ex10-108/small'),
  ('sm3-157', 'Alolan Muk-GX', 'https://images.scrydex.com/pokemon/sm3-157/small'),
  ('sv10-214', 'Regirock ex', 'https://images.scrydex.com/pokemon/sv10-214/small'),
  ('sv4-108', 'Sandy Shocks ex', 'https://images.scrydex.com/pokemon/sv4-108/small'),
  ('sm75-18', 'Kingdra-GX', 'https://images.scrydex.com/pokemon/sm75-18/small'),
  ('sma-SV30', 'Beldum', 'https://images.scrydex.com/pokemon/sma-SV30/small'),
  ('swsh4-182', 'Leon', 'https://images.scrydex.com/pokemon/swsh4-182/small'),
  ('xy5-86', 'Primal Groudon-EX', 'https://images.scrydex.com/pokemon/xy5-86/small'),
  ('me1-77', 'Mega Lucario ex', 'https://images.scrydex.com/pokemon/me1-77/small'),
  ('sv6pt5-98', 'Basic Darkness Energy', 'https://images.scrydex.com/pokemon/sv6pt5-98/small'),
  ('swsh10-113', 'Origin Forme Dialga V', 'https://images.scrydex.com/pokemon/swsh10-113/small'),
  ('swsh4-197', 'Opal', 'https://images.scrydex.com/pokemon/swsh4-197/small'),
  ('sm35-77', 'Zoroark-GX', 'https://images.scrydex.com/pokemon/sm35-77/small'),
  ('ex13-101', 'Mightyena ex', 'https://images.scrydex.com/pokemon/ex13-101/small'),
  ('sma-SV53', 'Alolan Ninetales-GX', 'https://images.scrydex.com/pokemon/sma-SV53/small'),
  ('sm3-134', 'Necrozma-GX', 'https://images.scrydex.com/pokemon/sm3-134/small'),
  ('sv8-247', 'Pikachu ex', 'https://images.scrydex.com/pokemon/sv8-247/small'),
  ('xy12-102', 'M Blastoise-EX', 'https://images.scrydex.com/pokemon/xy12-102/small'),
  ('swsh12-172', 'Reshiram V', 'https://images.scrydex.com/pokemon/swsh12-172/small'),
  ('sv8-226', 'Tatsugiri ex', 'https://images.scrydex.com/pokemon/sv8-226/small'),
  ('sv6pt5-37', 'Munkidori ex', 'https://images.scrydex.com/pokemon/sv6pt5-37/small'),
  ('ex10-102', 'Espeon ex', 'https://images.scrydex.com/pokemon/ex10-102/small'),
  ('sv1-237', 'Katy', 'https://images.scrydex.com/pokemon/sv1-237/small'),
  ('sv7-175', 'Bravery Charm', 'https://images.scrydex.com/pokemon/sv7-175/small'),
  ('swsh11-93', 'Aerodactyl VSTAR', 'https://images.scrydex.com/pokemon/swsh11-93/small'),
  ('sm4-63a', 'Guzzlord-GX', 'https://images.scrydex.com/pokemon/sm4-63a/small'),
  ('bw10-96', 'Virizion-EX', 'https://images.scrydex.com/pokemon/bw10-96/small'),
  ('me1-94', 'Mega Mawile ex', 'https://images.scrydex.com/pokemon/me1-94/small'),
  ('swsh4-202', 'Memory Capsule', 'https://images.scrydex.com/pokemon/swsh4-202/small'),
  ('xy9-76', 'Scizor-EX', 'https://images.scrydex.com/pokemon/xy9-76/small'),
  ('xy9-31', 'Palkia-EX', 'https://images.scrydex.com/pokemon/xy9-31/small'),
  ('swsh45-46', 'Yveltal', 'https://images.scrydex.com/pokemon/swsh45-46/small'),
  ('sm7-109', 'Rayquaza-GX', 'https://images.scrydex.com/pokemon/sm7-109/small'),
  ('zsv10pt5-160', 'Excadrill ex', 'https://images.scrydex.com/pokemon/zsv10pt5-160/small'),
  ('swsh12-188', 'Brandon', 'https://images.scrydex.com/pokemon/swsh12-188/small'),
  ('sv1-249', 'Arven', 'https://images.scrydex.com/pokemon/sv1-249/small'),
  ('me1-22', 'Mega Camerupt ex', 'https://images.scrydex.com/pokemon/me1-22/small'),
  ('sm2-144', 'Hau', 'https://images.scrydex.com/pokemon/sm2-144/small'),
  ('xy6-108', 'Winona', 'https://images.scrydex.com/pokemon/xy6-108/small'),
  ('swsh45sv-SV023', 'Galarian Darumaka', 'https://images.scrydex.com/pokemon/swsh45sv-SV023/small'),
  ('swsh2-200', 'Boss''s Orders', 'https://images.scrydex.com/pokemon/swsh2-200/small'),
  ('sm8-60', 'Suicune-GX', 'https://images.scrydex.com/pokemon/sm8-60/small'),
  ('sv8pt5-26', 'Glaceon ex', 'https://images.scrydex.com/pokemon/sv8pt5-26/small'),
  ('ecard2-148', 'Kingdra', 'https://images.scrydex.com/pokemon/ecard2-148/small'),
  ('me3-102', 'Mega Starmie ex', 'https://images.scrydex.com/pokemon/me3-102/small'),
  ('swsh45sv-SV112', 'Toxtricity V', 'https://images.scrydex.com/pokemon/swsh45sv-SV112/small'),
  ('swsh8-146', 'Lucario V', 'https://images.scrydex.com/pokemon/swsh8-146/small'),
  ('sv2-205', 'Eiscue', 'https://images.scrydex.com/pokemon/sv2-205/small'),
  ('sv2-213', 'Gothorita', 'https://images.scrydex.com/pokemon/sv2-213/small'),
  ('sv4pt5-69', 'Noivern ex', 'https://images.scrydex.com/pokemon/sv4pt5-69/small'),
  ('swsh11-57', 'Magnezone VSTAR', 'https://images.scrydex.com/pokemon/swsh11-57/small'),
  ('sv2-37', 'Skeledirge ex', 'https://images.scrydex.com/pokemon/sv2-37/small'),
  ('sv8pt5-174', 'Kieran', 'https://images.scrydex.com/pokemon/sv8pt5-174/small'),
  ('swsh8-26', 'Appletun V', 'https://images.scrydex.com/pokemon/swsh8-26/small'),
  ('sm11-247', 'Garchomp & Giratina-GX', 'https://images.scrydex.com/pokemon/sm11-247/small'),
  ('sm3-133', 'Tapu Fini-GX', 'https://images.scrydex.com/pokemon/sm3-133/small'),
  ('sma-SV42', 'Swablu', 'https://images.scrydex.com/pokemon/sma-SV42/small'),
  ('swsh7-91', 'Lycanroc V', 'https://images.scrydex.com/pokemon/swsh7-91/small'),
  ('sm10-228', 'Celesteela-GX', 'https://images.scrydex.com/pokemon/sm10-228/small'),
  ('bw11-RC25', 'Meloetta-EX', 'https://images.scrydex.com/pokemon/bw11-RC25/small'),
  ('zsv10pt5-170', 'N''s Plan', 'https://images.scrydex.com/pokemon/zsv10pt5-170/small'),
  ('swsh7-173', 'Suicune V', 'https://images.scrydex.com/pokemon/swsh7-173/small'),
  ('sm4-57', 'Buzzwole-GX', 'https://images.scrydex.com/pokemon/sm4-57/small'),
  ('ex12-87', 'Flygon ex', 'https://images.scrydex.com/pokemon/ex12-87/small'),
  ('sm2-165', 'Rare Candy', 'https://images.scrydex.com/pokemon/sm2-165/small'),
  ('sm1-12', 'Decidueye-GX', 'https://images.scrydex.com/pokemon/sm1-12/small'),
  ('sv3-229', 'Artazon', 'https://images.scrydex.com/pokemon/sv3-229/small'),
  ('sm75-73', 'Salamence-GX', 'https://images.scrydex.com/pokemon/sm75-73/small'),
  ('sm8-230', 'Counter Gain', 'https://images.scrydex.com/pokemon/sm8-230/small'),
  ('sv4-224', 'Cofagrigus ex', 'https://images.scrydex.com/pokemon/sv4-224/small'),
  ('sv2-263', 'Ting-Lu ex', 'https://images.scrydex.com/pokemon/sv2-263/small'),
  ('swsh8-86', 'Pikachu V', 'https://images.scrydex.com/pokemon/swsh8-86/small'),
  ('ex3-95', 'Magcargo ex', 'https://images.scrydex.com/pokemon/ex3-95/small'),
  ('swsh7-180', 'Espeon V', 'https://images.scrydex.com/pokemon/swsh7-180/small'),
  ('swsh12pt5gg-GG68', 'Origin Forme Dialga VSTAR', 'https://images.scrydex.com/pokemon/swsh12pt5gg-GG68/small'),
  ('sv8pt5-58', 'Cornerstone Mask Ogerpon ex', 'https://images.scrydex.com/pokemon/sv8pt5-58/small'),
  ('sv10-66', 'Dondozo ex', 'https://images.scrydex.com/pokemon/sv10-66/small'),
  ('sma-SV39', 'Gabite', 'https://images.scrydex.com/pokemon/sma-SV39/small'),
  ('sm10-140', 'Whimsicott-GX', 'https://images.scrydex.com/pokemon/sm10-140/small'),
  ('sv9-11', 'Amoonguss ex', 'https://images.scrydex.com/pokemon/sv9-11/small'),
  ('sv5-190', 'Wugtrio ex', 'https://images.scrydex.com/pokemon/sv5-190/small'),
  ('swsh11-176', 'Rotom V', 'https://images.scrydex.com/pokemon/swsh11-176/small'),
  ('swsh12-196', 'Serperior VSTAR', 'https://images.scrydex.com/pokemon/swsh12-196/small'),
  ('sm11-241', 'Raichu & Alolan Raichu-GX', 'https://images.scrydex.com/pokemon/sm11-241/small'),
  ('sm11-221', 'Raichu & Alolan Raichu-GX', 'https://images.scrydex.com/pokemon/sm11-221/small'),
  ('sv3pt5-194', 'Bill''s Transfer', 'https://images.scrydex.com/pokemon/sv3pt5-194/small'),
  ('xy2-12', 'Charizard-EX', 'https://images.scrydex.com/pokemon/xy2-12/small'),
  ('xy4-23', 'Manectric-EX', 'https://images.scrydex.com/pokemon/xy4-23/small'),
  ('rsv10pt5-124', 'Gothita', 'https://images.scrydex.com/pokemon/rsv10pt5-124/small'),
  ('sm2-138', 'Lycanroc-GX', 'https://images.scrydex.com/pokemon/sm2-138/small'),
  ('g1-28a', 'Jolteon-EX', 'https://images.scrydex.com/pokemon/g1-28a/small'),
  ('swsh8-185', 'Genesect V', 'https://images.scrydex.com/pokemon/swsh8-185/small'),
  ('sv10-189', 'Rapidash', 'https://images.scrydex.com/pokemon/sv10-189/small'),
  ('sm5-142', 'Xurkitree-GX', 'https://images.scrydex.com/pokemon/sm5-142/small'),
  ('rsv10pt5-102', 'Lampent', 'https://images.scrydex.com/pokemon/rsv10pt5-102/small'),
  ('sm2-60', 'Tapu Lele-GX', 'https://images.scrydex.com/pokemon/sm2-60/small'),
  ('sv10-238', 'Team Rocket''s Giovanni', 'https://images.scrydex.com/pokemon/sv10-238/small'),
  ('swsh6-206', 'Sandaconda VMAX', 'https://images.scrydex.com/pokemon/swsh6-206/small'),
  ('swsh12pt5-147', 'Elesa''s Sparkle', 'https://images.scrydex.com/pokemon/swsh12pt5-147/small'),
  ('ex7-104', 'Rocket''s Snorlax ex', 'https://images.scrydex.com/pokemon/ex7-104/small'),
  ('me1-164', 'Mega Kangaskhan ex', 'https://images.scrydex.com/pokemon/me1-164/small'),
  ('sv8pt5-28', 'Pikachu ex', 'https://images.scrydex.com/pokemon/sv8pt5-28/small'),
  ('swsh11-178', 'Enamorus V', 'https://images.scrydex.com/pokemon/swsh11-178/small'),
  ('sv6-169', 'Sunflora', 'https://images.scrydex.com/pokemon/sv6-169/small'),
  ('swsh6-177', 'Galarian Moltres V', 'https://images.scrydex.com/pokemon/swsh6-177/small'),
  ('sv1-65', 'Magnezone ex', 'https://images.scrydex.com/pokemon/sv1-65/small'),
  ('sma-SV56', 'Greninja-GX', 'https://images.scrydex.com/pokemon/sma-SV56/small'),
  ('sv8-130', 'Archaludon ex', 'https://images.scrydex.com/pokemon/sv8-130/small'),
  ('xy5-149', 'Primal Kyogre-EX', 'https://images.scrydex.com/pokemon/xy5-149/small'),
  ('xy10-120', 'Genesect-EX', 'https://images.scrydex.com/pokemon/xy10-120/small'),
  ('me2pt5-258', 'Cheren', 'https://images.scrydex.com/pokemon/me2pt5-258/small'),
  ('sv4pt5-75', 'Squawkabilly ex', 'https://images.scrydex.com/pokemon/sv4pt5-75/small'),
  ('sv10-223', 'Team Rocket''s Archer', 'https://images.scrydex.com/pokemon/sv10-223/small'),
  ('sv6pt5-76', 'Cufant', 'https://images.scrydex.com/pokemon/sv6pt5-76/small'),
  ('sv4pt5-241', 'Chi-Yu ex', 'https://images.scrydex.com/pokemon/sv4pt5-241/small'),
  ('sv5-204', 'Gouging Fire ex', 'https://images.scrydex.com/pokemon/sv5-204/small'),
  ('sm35-76', 'Mewtwo-GX', 'https://images.scrydex.com/pokemon/sm35-76/small'),
  ('me2pt5-283', 'Mega Hawlucha ex', 'https://images.scrydex.com/pokemon/me2pt5-283/small'),
  ('xy11-110', 'Magearna-EX', 'https://images.scrydex.com/pokemon/xy11-110/small'),
  ('me2pt5-281', 'Team Rocket''s Mewtwo ex', 'https://images.scrydex.com/pokemon/me2pt5-281/small'),
  ('sv1-239', 'Penny', 'https://images.scrydex.com/pokemon/sv1-239/small'),
  ('sm2-92', 'Sylveon-GX', 'https://images.scrydex.com/pokemon/sm2-92/small'),
  ('sv4-266', 'Reversal Energy', 'https://images.scrydex.com/pokemon/sv4-266/small'),
  ('swsh1-208', 'Marnie', 'https://images.scrydex.com/pokemon/swsh1-208/small'),
  ('sv10-203', 'Team Rocket''s Meowth', 'https://images.scrydex.com/pokemon/sv10-203/small'),
  ('swsh9-156', 'Lumineon V', 'https://images.scrydex.com/pokemon/swsh9-156/small'),
  ('sm3-149', 'Tapu Bulu-GX', 'https://images.scrydex.com/pokemon/sm3-149/small'),
  ('me1-146', 'Marshadow', 'https://images.scrydex.com/pokemon/me1-146/small'),
  ('sv4-213', 'Swablu', 'https://images.scrydex.com/pokemon/sv4-213/small'),
  ('swsh11-196', 'Volo', 'https://images.scrydex.com/pokemon/swsh11-196/small'),
  ('sv8pt5-167', 'Eevee ex', 'https://images.scrydex.com/pokemon/sv8pt5-167/small'),
  ('bw6-71', 'Terrakion-EX', 'https://images.scrydex.com/pokemon/bw6-71/small'),
  ('swsh45sv-SV060', 'Dreepy', 'https://images.scrydex.com/pokemon/swsh45sv-SV060/small'),
  ('cel25-16', 'Zacian V', 'https://images.scrydex.com/pokemon/cel25-16/small'),
  ('swsh7-199', 'Aroma Lady', 'https://images.scrydex.com/pokemon/swsh7-199/small'),
  ('zsv10pt5-115', 'Eelektross', 'https://images.scrydex.com/pokemon/zsv10pt5-115/small'),
  ('swsh45sv-SV120', 'Dubwool V', 'https://images.scrydex.com/pokemon/swsh45sv-SV120/small'),
  ('zsv10pt5-108', 'Alomomola', 'https://images.scrydex.com/pokemon/zsv10pt5-108/small'),
  ('sm3-130', 'Tapu Bulu-GX', 'https://images.scrydex.com/pokemon/sm3-130/small'),
  ('swsh45sv-SV104', 'Dubwool', 'https://images.scrydex.com/pokemon/swsh45sv-SV104/small'),
  ('g1-RC21', 'Sylveon-EX', 'https://images.scrydex.com/pokemon/g1-RC21/small'),
  ('sm6-140', 'Ultra Necrozma-GX', 'https://images.scrydex.com/pokemon/sm6-140/small'),
  ('xy6-101', 'Latios-EX', 'https://images.scrydex.com/pokemon/xy6-101/small'),
  ('xy2-88a', 'Blacksmith', 'https://images.scrydex.com/pokemon/xy2-88a/small'),
  ('sm1-142', 'Umbreon-GX', 'https://images.scrydex.com/pokemon/sm1-142/small'),
  ('sm3-20', 'Charizard-GX', 'https://images.scrydex.com/pokemon/sm3-20/small'),
  ('sv10-195', 'Clamperl', 'https://images.scrydex.com/pokemon/sv10-195/small'),
  ('sv4-236', 'Mela', 'https://images.scrydex.com/pokemon/sv4-236/small'),
  ('sm1-35', 'Lapras-GX', 'https://images.scrydex.com/pokemon/sm1-35/small'),
  ('ex5-102', 'Groudon', 'https://images.scrydex.com/pokemon/ex5-102/small'),
  ('sv8-217', 'Milotic ex', 'https://images.scrydex.com/pokemon/sv8-217/small'),
  ('swsh45sv-SV113', 'Toxtricity VMAX', 'https://images.scrydex.com/pokemon/swsh45sv-SV113/small'),
  ('me3-111', 'Lumiose City', 'https://images.scrydex.com/pokemon/me3-111/small'),
  ('sv6-183', 'Timburr', 'https://images.scrydex.com/pokemon/sv6-183/small'),
  ('ex1-103', 'Sneasel ex', 'https://images.scrydex.com/pokemon/ex1-103/small'),
  ('sm3-150', 'Charizard-GX', 'https://images.scrydex.com/pokemon/sm3-150/small'),
  ('swsh4-198', 'Galarian Obstagoon', 'https://images.scrydex.com/pokemon/swsh4-198/small'),
  ('swsh45sv-SV058', 'Alcremie', 'https://images.scrydex.com/pokemon/swsh45sv-SV058/small'),
  ('sma-SV46', 'Leafeon-GX', 'https://images.scrydex.com/pokemon/sma-SV46/small'),
  ('sv4-250', 'Sandy Shocks ex', 'https://images.scrydex.com/pokemon/sv4-250/small'),
  ('rsv10pt5-113', 'Vanilluxe', 'https://images.scrydex.com/pokemon/rsv10pt5-113/small'),
  ('rsv10pt5-120', 'Swoobat', 'https://images.scrydex.com/pokemon/rsv10pt5-120/small'),
  ('swsh12pt5gg-GG61', 'Gardenia''s Vigor', 'https://images.scrydex.com/pokemon/swsh12pt5gg-GG61/small'),
  ('swsh12pt5gg-GG41', 'Raikou V', 'https://images.scrydex.com/pokemon/swsh12pt5gg-GG41/small'),
  ('sv4-207', 'Brute Bonnet', 'https://images.scrydex.com/pokemon/sv4-207/small'),
  ('swsh6-162', 'Volcanion V', 'https://images.scrydex.com/pokemon/swsh6-162/small'),
  ('xy7-95', 'Steven', 'https://images.scrydex.com/pokemon/xy7-95/small'),
  ('me1-165', 'Acerola''s Mischief', 'https://images.scrydex.com/pokemon/me1-165/small'),
  ('sm12-215', 'Blastoise & Piplup-GX', 'https://images.scrydex.com/pokemon/sm12-215/small'),
  ('swsh7-217', 'Rayquaza VMAX', 'https://images.scrydex.com/pokemon/swsh7-217/small'),
  ('sv1-32', 'Arcanine ex', 'https://images.scrydex.com/pokemon/sv1-32/small'),
  ('sv6pt5-92', 'Fezandipiti ex', 'https://images.scrydex.com/pokemon/sv6pt5-92/small'),
  ('swsh45sv-SV025', 'Sobble', 'https://images.scrydex.com/pokemon/swsh45sv-SV025/small'),
  ('sv3-135', 'Absol ex', 'https://images.scrydex.com/pokemon/sv3-135/small'),
  ('swsh35-16', 'Gardevoir V', 'https://images.scrydex.com/pokemon/swsh35-16/small'),
  ('swsh7-169', 'Flareon V', 'https://images.scrydex.com/pokemon/swsh7-169/small'),
  ('sm11-220', 'Raichu & Alolan Raichu-GX', 'https://images.scrydex.com/pokemon/sm11-220/small'),
  ('ex15-96', 'Latios ex δ', 'https://images.scrydex.com/pokemon/ex15-96/small'),
  ('swsh9-88', 'Honchkrow V', 'https://images.scrydex.com/pokemon/swsh9-88/small'),
  ('sm8-200', 'Suicune-GX', 'https://images.scrydex.com/pokemon/sm8-200/small'),
  ('sm7-182', 'Rainbow Brush', 'https://images.scrydex.com/pokemon/sm7-182/small'),
  ('swsh4-171', 'Ampharos V', 'https://images.scrydex.com/pokemon/swsh4-171/small'),
  ('swsh4-199', 'Oranguru', 'https://images.scrydex.com/pokemon/swsh4-199/small'),
  ('sv8pt5-134', 'Atticus', 'https://images.scrydex.com/pokemon/sv8pt5-134/small'),
  ('swsh10-191', 'Heatran VMAX', 'https://images.scrydex.com/pokemon/swsh10-191/small'),
  ('me2pt5-220', 'Dustox', 'https://images.scrydex.com/pokemon/me2pt5-220/small'),
  ('g1-RC28', 'Flareon-EX', 'https://images.scrydex.com/pokemon/g1-RC28/small'),
  ('sv8-214', 'Braviary', 'https://images.scrydex.com/pokemon/sv8-214/small'),
  ('sm5-147', 'Palkia-GX', 'https://images.scrydex.com/pokemon/sm5-147/small'),
  ('swsh5-109', 'Corviknight V', 'https://images.scrydex.com/pokemon/swsh5-109/small'),
  ('xy9-117', 'Espeon-EX', 'https://images.scrydex.com/pokemon/xy9-117/small'),
  ('swsh8-264', 'Sidney', 'https://images.scrydex.com/pokemon/swsh8-264/small'),
  ('sv8-68', 'Kilowattrel ex', 'https://images.scrydex.com/pokemon/sv8-68/small'),
  ('sm3-158', 'Darkrai-GX', 'https://images.scrydex.com/pokemon/sm3-158/small'),
  ('swsh2-175', 'Rillaboom V', 'https://images.scrydex.com/pokemon/swsh2-175/small'),
  ('swsh12pt5gg-GG53', 'Hoopa V', 'https://images.scrydex.com/pokemon/swsh12pt5gg-GG53/small'),
  ('sv2-257', 'Wo-Chien ex', 'https://images.scrydex.com/pokemon/sv2-257/small'),
  ('sv2-236', 'Chien-Pao ex', 'https://images.scrydex.com/pokemon/sv2-236/small'),
  ('swsh5-51', 'Tapu Koko VMAX', 'https://images.scrydex.com/pokemon/swsh5-51/small'),
  ('swsh45-64', 'Alcremie V', 'https://images.scrydex.com/pokemon/swsh45-64/small'),
  ('swsh10-177', 'Origin Forme Dialga V', 'https://images.scrydex.com/pokemon/swsh10-177/small'),
  ('me2-126', 'Rotom ex', 'https://images.scrydex.com/pokemon/me2-126/small'),
  ('sv9-51', 'Tapu Koko ex', 'https://images.scrydex.com/pokemon/sv9-51/small'),
  ('swsh45sv-SV027', 'Inteleon', 'https://images.scrydex.com/pokemon/swsh45sv-SV027/small'),
  ('swsh7-92', 'Lycanroc VMAX', 'https://images.scrydex.com/pokemon/swsh7-92/small'),
  ('sv3-215', 'Charizard ex', 'https://images.scrydex.com/pokemon/sv3-215/small'),
  ('ex9-92', 'Camerupt ex', 'https://images.scrydex.com/pokemon/ex9-92/small'),
  ('sv2-248', 'Boss''s Orders (Ghetsis)', 'https://images.scrydex.com/pokemon/sv2-248/small'),
  ('swsh6-222', 'Electrode', 'https://images.scrydex.com/pokemon/swsh6-222/small'),
  ('sm8-213', 'Professor Elm''s Lecture', 'https://images.scrydex.com/pokemon/sm8-213/small'),
  ('sv2-194', 'Heracross', 'https://images.scrydex.com/pokemon/sv2-194/small'),
  ('sv3pt5-188', 'Alakazam ex', 'https://images.scrydex.com/pokemon/sv3pt5-188/small'),
  ('sv3-66', 'Tyranitar ex', 'https://images.scrydex.com/pokemon/sv3-66/small'),
  ('ex1-98', 'Hitmonchan ex', 'https://images.scrydex.com/pokemon/ex1-98/small'),
  ('sma-SV68', 'Buzzwole-GX', 'https://images.scrydex.com/pokemon/sma-SV68/small'),
  ('sv10-239', 'Ethan''s Ho-Oh ex', 'https://images.scrydex.com/pokemon/sv10-239/small'),
  ('sm75-70', 'Zinnia', 'https://images.scrydex.com/pokemon/sm75-70/small'),
  ('zsv10pt5-163', 'N''s Plan', 'https://images.scrydex.com/pokemon/zsv10pt5-163/small'),
  ('swsh10-193', 'Hisuian Typhlosion VSTAR', 'https://images.scrydex.com/pokemon/swsh10-193/small'),
  ('swsh11-49', 'Kyurem VMAX', 'https://images.scrydex.com/pokemon/swsh11-49/small'),
  ('sm10-195a', 'Dedenne-GX', 'https://images.scrydex.com/pokemon/sm10-195a/small'),
  ('swsh4-82', 'Zacian', 'https://images.scrydex.com/pokemon/swsh4-82/small'),
  ('me2pt5-125', 'Mega Gengar ex', 'https://images.scrydex.com/pokemon/me2pt5-125/small'),
  ('me2-106', 'Meowth', 'https://images.scrydex.com/pokemon/me2-106/small'),
  ('swsh6-227', 'Fog Crystal', 'https://images.scrydex.com/pokemon/swsh6-227/small'),
  ('swsh10tg-TG29', 'Ice Rider Calyrex VMAX', 'https://images.scrydex.com/pokemon/swsh10tg-TG29/small'),
  ('sv2-86', 'Slowking ex', 'https://images.scrydex.com/pokemon/sv2-86/small'),
  ('sm35-75', 'Raichu-GX', 'https://images.scrydex.com/pokemon/sm35-75/small'),
  ('bw5-109', 'Gardevoir', 'https://images.scrydex.com/pokemon/bw5-109/small'),
  ('sm10-109', 'Honchkrow-GX', 'https://images.scrydex.com/pokemon/sm10-109/small'),
  ('xy3-55', 'M Lucario-EX', 'https://images.scrydex.com/pokemon/xy3-55/small'),
  ('sv8-86', 'Sylveon ex', 'https://images.scrydex.com/pokemon/sv8-86/small'),
  ('swsh45sv-SV013', 'Flapple', 'https://images.scrydex.com/pokemon/swsh45sv-SV013/small'),
  ('sma-SV37', 'Altaria', 'https://images.scrydex.com/pokemon/sma-SV37/small'),
  ('sv4-203', 'Slither Wing', 'https://images.scrydex.com/pokemon/sv4-203/small'),
  ('xy7-85', 'M Sceptile-EX', 'https://images.scrydex.com/pokemon/xy7-85/small'),
  ('xy4-119', 'Xerosic', 'https://images.scrydex.com/pokemon/xy4-119/small'),
  ('xy10-54a', 'Zygarde-EX', 'https://images.scrydex.com/pokemon/xy10-54a/small'),
  ('swsh12-183', 'Regidrago V', 'https://images.scrydex.com/pokemon/swsh12-183/small')
ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, image_small = EXCLUDED.image_small;
